name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build web app
      run: npx webpack --mode production
      
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install Capacitor
      run: |
        npm install -g @capacitor/cli
        npm install @capacitor/core @capacitor/android @capacitor/camera
        
    - name: Initialize Capacitor
      run: |
        npx cap init "iOS Camera App" "com.iosCamera.app" --web-dir=dist --npm-client=npm
        
    - name: Add Android platform
      run: npx cap add android
      
    - name: Copy web assets
      run: npx cap copy android
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Set gradlew permissions
      run: |
        if [ -f android/gradlew ]; then
          chmod +x android/gradlew
        fi
        
    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleDebug --no-daemon --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ios-camera-app-debug
        path: android/app/build/outputs/apk/debug/*.apk
        retention-days: 30
        if-no-files-found: error