name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build web app
      run: npx webpack --mode production
      
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
      
    - name: Check versions
      run: |
        node --version
        npm --version
        java -version
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        
    - name: Install Capacitor
      run: |
        npm install -g @capacitor/cli@latest
        npm install @capacitor/core @capacitor/android @capacitor/camera @capacitor/splash-screen --save
        
    - name: Initialize Capacitor
      run: |
        # Use existing capacitor.config.js if available, otherwise init
        if [ ! -f "capacitor.config.js" ]; then
          npx cap init "iOS Camera App" "com.iosCamera.app" --web-dir=dist
        fi
        cat capacitor.config.js
        
    - name: Add Android platform
      run: npx cap add android
      
    - name: Copy Android configuration
      run: |
        mkdir -p android/app/src/main/res/xml
        cp android/app/src/main/AndroidManifest.xml android/app/src/main/AndroidManifest.xml || true
        cp android/app/src/main/res/xml/file_paths.xml android/app/src/main/res/xml/file_paths.xml || true
      
    - name: Copy web assets and sync
      run: |
        npx cap copy android
        npx cap sync android
        
    - name: Setup Gradle properties
      run: |
        if [ ! -f android/gradle.properties ]; then
          cp gradle.properties android/ || echo "No gradle.properties to copy"
        fi
      
    - name: Set gradlew permissions
      run: |
        if [ -f android/gradlew ]; then
          chmod +x android/gradlew
        fi
        
    - name: Build Android APK
      run: |
        cd android
        echo "Building with Java $(java -version 2>&1 | head -n 1)"
        ./gradlew assembleDebug --no-daemon --stacktrace --info
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ios-camera-app-debug
        path: android/app/build/outputs/apk/debug/*.apk
        retention-days: 30
        if-no-files-found: error